import random

BASE_QUERIES = [
    "What is a large language model?",
    "Explain machine learning",
    "What is deep learning?",
    "What is artificial intelligence?",
    "Explain neural networks",
    "What is overfitting in ML?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is reinforcement learning?",
    "What is natural language processing?",
    "Explain transformers in AI",
    "What is GPT?",
    "What is ChatGPT?",
    "What is tokenization in NLP?",
    "What is an embedding?",
    "Explain cosine similarity",
    "What is a vector database?",
    "What is LangChain?",
    "What is prompt engineering?",
    "What is fine-tuning?",
    "What is RAG (retrieval augmented generation)?",
    "What is a chatbot?",
    "What is a neural network layer?",
    "What is backpropagation?",
    "What is gradient descent?",
    "What is a dataset?",
    "What is training vs testing data?",
    "What is model inference?",
    "What is a parameter in ML?",
    "What is a hyperparameter?",
    "What is accuracy in ML?",
    "What is precision and recall?",
    "What is F1 score?",
    "What is bias in ML?",
    "What is variance in ML?",
    "Explain bias-variance tradeoff",
    "What is an API?",
    "What is FastAPI?",
    "What is Streamlit?",
    "What is caching in AI systems?",
    "What is GPTCache?",
    "What is semantic search?",
    "What is cosine distance?",
    "What is latency?",
    "What is throughput?",
    "What is cloud computing?",
    "What is edge computing?",
    "What is a GPU?",
    "What is parallel processing?",
    "What is Python used for?",
    "How do transformers work in NLP?",
    "What is attention mechanism?",
    "Explain self-attention in transformers",
    "What is BERT?",
    "What is T5 model?",
    "What is Claude AI?",
    "How does semantic caching improve performance?",
    "What is vector similarity search?",
    "Explain FAISS (Facebook AI Similarity Search)",
    "What is Pinecone vector database?",
    "How does Weaviate work?",
    "What is Milvus?",
    "Explain feature extraction",
    "What is dimensionality reduction?",
    "What is PCA (Principal Component Analysis)?",
    "Explain t-SNE visualization",
    "What is clustering?",
    "What is K-means clustering?",
    "Explain hierarchical clustering",
    "What is DBSCAN?",
    "What is anomaly detection?",
    "Explain isolation forest",
    "What is classification?",
    "What is logistic regression?",
    "Explain decision trees",
    "What is random forest?",
    "What is gradient boosting?",
    "Explain XGBoost algorithm",
    "What is LightGBM?",
    "What is CatBoost?",
    "Explain SVM (Support Vector Machines)",
    "What is Naive Bayes?",
    "Explain k-NN (k-Nearest Neighbors)",
    "What is ensemble learning?",
    "Explain bagging and boosting",
    "What is AdaBoost?",
    "What is regularization in ML?",
    "Explain L1 and L2 regularization",
    "What is dropout in neural networks?",
    "What is batch normalization?",
    "Explain activation functions",
    "What is ReLU activation?",
    "What is sigmoid function?",
    "What is tanh activation?",
    "Explain softmax function",
    "What is loss function?",
    "What is cross-entropy loss?",
    "Explain mean squared error (MSE)",
    "What is optimization in ML?",
    "Explain SGD (Stochastic Gradient Descent)",
    "What is Adam optimizer?",
    "Explain RMSprop optimizer",
    "What is learning rate in neural networks?",
    "Explain learning rate scheduling",
    "What is early stopping?",
    "What is cross-validation?",
    "Explain k-fold cross-validation",
    "What is confusion matrix?",
    "Explain ROC curve",
    "What is AUC (Area Under Curve)?",
    "What is mean average precision?",
    "Explain BLEU score",
    "What is ROUGE metric?",
    "Explain METEOR score",
    "What is perplexity in NLP?",
    "What is BERT score?",
    "Explain human evaluation in NLP",
    "What is zero-shot learning?",
    "What is few-shot learning?",
    "Explain meta-learning",
    "What is transfer learning?",
    "Explain domain adaptation",
    "What is multitask learning?",
    "Explain continual learning",
    "What is catastrophic forgetting?",
    "What is active learning?",
    "Explain curriculum learning",
    "What is data augmentation?",
    "Explain mixup data augmentation",
    "What is cutout regularization?",
    "What is synthetic data generation?",
    "Explain GANs (Generative Adversarial Networks)",
    "What is VAE (Variational Autoencoder)?",
    "What is a diffusion model?",
    "Explain auto-regressive models",
    "What is masked language modeling?",
    "Explain next sentence prediction",
    "What is language model pretraining?",
    "What is instruction tuning?",
    "Explain RLHF (Reinforcement Learning from Human Feedback)",
    "What is constitutional AI?",
    "Explain in-context learning",
    "What is chain-of-thought prompting?",
    "What is tree-of-thought?",
    "Explain retrieval augmented generation",
    "What is semantic search vs keyword search?",
    "Explain dense passage retrieval",
    "What is BM25 ranking?",
    "What is TF-IDF?",
    "Explain Okapi BM25",
    "What is colbert retriever?",
    "Explain cross-encoder models",
    "What is bi-encoder architecture?",
    "What is query expansion?",
    "Explain pseudo-relevance feedback",
    "What is query rewriting?",
    "Explain multi-hop reasoning",
    "What is knowledge graph reasoning?",
    "Explain entity linking",
    "What is relation extraction?",
    "What is named entity recognition?",
    "Explain POS (Part-of-Speech) tagging",
    "What is dependency parsing?",
    "Explain constituency parsing",
    "What is semantic role labeling?",
    "Explain coreference resolution",
    "What is sentiment analysis?",
    "Explain aspect-based sentiment analysis",
    "What is emotion detection?",
    "Explain toxic comment detection",
    "What is spam detection in NLP?",
    "Explain text classification",
    "What is multi-label classification?",
    "Explain hierarchical classification",
    "What is intent detection?",
    "Explain slot filling",
    "What is dialogue systems?",
    "Explain conversational AI",
    "What is task-oriented dialogue?",
    "Explain open-domain dialogue",
    "What is question answering?",
    "Explain reading comprehension models?",
    "What is extractive QA?",
    "Explain generative QA",
    "What is machine translation?",
    "Explain neural machine translation",
    "What is back-translation data augmentation?",
    "Explain pivot-based machine translation",
    "What is summarization?",
    "Explain extractive summarization?",
    "What is abstractive summarization?",
    "Explain multi-document summarization",
    "What is paraphrase generation?",
    "Explain text simplification",
    "What is style transfer in NLP?",
    "Explain grammatical error correction",
    "What is spelling correction?",
    "Explain text-to-speech synthesis",
    "What is speech recognition?",
    "Explain acoustic models",
    "What is language models for speech?",
    "Explain speech-to-text systems",
    "What is speaker recognition?",
    "Explain speaker diarization?",
    "What is emotion recognition from speech?",
    "Explain keyword spotting",
    "What is voice activity detection?"
]


def generate_workload(size=4, repeat_ratio=0.0):
    unique_count = max(1, int(size * (1 - repeat_ratio)))
    duplicate_count = size - unique_count

    queries = []

    for i in range(unique_count):
        q = random.choice(BASE_QUERIES)
        queries.append(f"{q} (variation {i})")

    for i in range(duplicate_count):
        queries.append(random.choice(queries))

    return queries



def generate_all_workloads(size=4):
    return {
        "W1_0%": generate_workload(size, 0.0),
        "W2_25%": generate_workload(size, 0.25),
        "W3_50%": generate_workload(size, 0.5),
        "W4_75%": generate_workload(size, 0.75),
    }


if __name__ == "__main__":
    workloads = generate_all_workloads(size=4)

    for name, data in workloads.items():
        print(f"\n{name} SAMPLE:")
        print(data)
